language: python
python:
  - 3.7

notifications:
  email: false

before_install:
    - sudo apt-get update
    - sudo apt-get -y install tabix

install:
  - pip install pipenv
  - pipenv install

script:
  - pytest tests/
  - mypy --ignore-missing-imports variant/
