services:
  uta:
    # Test:
    # psql -XAt postgres://anonymous@localhost/uta -c 'select count(*) from uta_20210129b.transcript'
    # 314227
    image: biocommons/uta:uta_20210129b
    environment:
      - POSTGRES_PASSWORD=some-password-that-you-make-up
    volumes:
      - uta_vol:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  uta_vol:
    external: true
