version: "3"

services:
  seqrepo-rest-service:
    expose:
      - 5000
    ports:
      - 5000:5000
    image: biocommons/seqrepo-rest-service:latest
    volumes:
      - /usr/local/share/seqrepo:/usr/local/share/seqrepo

  uta:
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    image: biocommons/uta:uta_20180821
    volumes:
      - ./uta_20180821:/var/lib/postgresql/data

volumes:
  seqrepo_vol:
    external: true
  uta_vol:
    external: true