name: checks
on: [push, pull_request]
jobs:
  deps:
    name: deps py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install pipenv==2023.7.23  # pin version where --skip-lock exists
          pipenv install --skip-lock  # this is what Elastic beanstalk uses
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: python3 -m pip install ".[dev]"

      - name: Check style
        run: python3 -m ruff check . && python3 -m ruff format --check .

  precommit_hooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmd:
          - "end-of-file-fixer"
          - "trailing-whitespace"
          - "mixed-line-ending"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: ${{ matrix.cmd }} --all-files
